import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_Components/navbar/navbar";
import { Toaster } from "react-hot-toast";
import CartContextProvider from "./_Components/context/CartContext";
import Footer from "./_Components/footer/Footer";
import MySessionProvider from "./_Components/MySessionProvider/MySessionProvider";
import WishListProvider from "./_Components/context/WishListContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full flex flex-col flex-col`}
      >
        <MySessionProvider>
          <CartContextProvider>
                  <WishListProvider>
                      <Navbar />

                      <div className="container mx-auto flex-1">
                        {children}
                        <Toaster />
                      </div>

                      <Footer />
                  </WishListProvider>
          </CartContextProvider>
        </MySessionProvider>
      </body>
    </html>
  );
}
